<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select dateFriday, 27 August 2027</name>
   <tag></tag>
   <elementGuidId>1e66d3ff-329b-43bb-ba37-c7554d68a6b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='date_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#date_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#date_id</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2084ee61-0ae8-4522-be7d-8b23c578a4f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-border</value>
      <webElementGuid>6e1a5d9f-2c47-402e-959b-74e9e93714c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date_id</value>
      <webElementGuid>f6821cf8-cce3-4fa2-b346-e263e6757c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>date_id</value>
      <webElementGuid>d67e6846-3a53-4627-a0c7-14ef72bafd65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select dateFriday, 27 August 2027</value>
      <webElementGuid>4f31cdf3-1346-4f06-9ab8-cc229052b0a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;date_id&quot;)</value>
      <webElementGuid>988a8347-77de-467c-ad0b-e78865ed4920</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='date_id']</value>
      <webElementGuid>b35f11c1-a2c7-4ba0-bf71-07bb58704e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='proj-landing']/form/div[2]/div/select</value>
      <webElementGuid>751acc4d-66bf-40d6-b321-20e779e51d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pick available date'])[1]/following::select[1]</value>
      <webElementGuid>d4318560-f653-4636-8d83-5b191f87f2b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a class'])[1]/following::select[2]</value>
      <webElementGuid>e9505d78-917c-40ea-a205-45af3314f102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pick available hour'])[1]/preceding::select[1]</value>
      <webElementGuid>90671298-bbb1-4d6c-8971-cee0876d03b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity'])[1]/preceding::select[2]</value>
      <webElementGuid>987d7da3-0ea6-4912-a90e-983029c6389e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>a3f4c68b-d799-452a-ace0-de78bb128fc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'date_id' and @id = 'date_id' and (text() = 'Select dateFriday, 27 August 2027' or . = 'Select dateFriday, 27 August 2027')]</value>
      <webElementGuid>6a2a7e6c-3418-4c18-95ae-9870d24a9c4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
