<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Get strong today</name>
   <tag></tag>
   <elementGuidId>ec4983a5-53d5-44a8-bc46-b6c3764cc9c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slide-12-layer-10']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#slide-12-layer-10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Get strong today&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3b19bc3f-0ebc-4713-a596-a31fa1ac0dc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tp-caption   tp-resizeme</value>
      <webElementGuid>cc41f400-881d-4254-a3e2-7e1b063c8b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>slide-12-layer-10</value>
      <webElementGuid>9409bd71-e81d-475d-a407-3ef15a377b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-x</name>
      <type>Main</type>
      <value>['left','left','left','left']</value>
      <webElementGuid>b65e0150-8604-433d-a1e1-d24d41cf4f57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hoffset</name>
      <type>Main</type>
      <value>['0','0','0','15']</value>
      <webElementGuid>9633bb23-8be8-4f7d-884e-8e4b657f59a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-y</name>
      <type>Main</type>
      <value>['middle','middle','middle','middle']</value>
      <webElementGuid>bbe41ca6-6579-40c8-88f1-786aa666a4de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-voffset</name>
      <type>Main</type>
      <value>['0','-16','-116','-36']</value>
      <webElementGuid>9298b435-c7de-42dc-b17e-81978e50755d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fontsize</name>
      <type>Main</type>
      <value>['95','95','95','50']</value>
      <webElementGuid>202e8a26-5e99-48ee-8a41-554f188f8dce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lineheight</name>
      <type>Main</type>
      <value>['90','90','90','50']</value>
      <webElementGuid>6cd45735-6c1f-4beb-8595-fd7205f56c87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-letterspacing</name>
      <type>Main</type>
      <value>['19','19','19','10']</value>
      <webElementGuid>147aa6d6-e146-4ad5-a342-c6ff7df8e021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-width</name>
      <type>Main</type>
      <value>['595','585','586','219']</value>
      <webElementGuid>2c7e4619-0591-4348-a7ea-82c73e78c1a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-height</name>
      <type>Main</type>
      <value>['181','181','181','151']</value>
      <webElementGuid>83b44476-cfcb-4fcf-ac64-94d92c8e6081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-whitespace</name>
      <type>Main</type>
      <value>normal</value>
      <webElementGuid>59d4465a-8f57-4ab4-b624-468516d53f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8ca944cc-49a3-45e2-bc1c-e806d74bd54e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-responsive_offset</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>74b21244-0d28-4235-b26c-367e3b1ce6f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frames</name>
      <type>Main</type>
      <value>[{&quot;delay&quot;:600,&quot;speed&quot;:700,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power2.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]</value>
      <webElementGuid>a8fa0b9d-cec0-43fb-a3de-e864e367ba7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-textalign</name>
      <type>Main</type>
      <value>['inherit','inherit','inherit','inherit']</value>
      <webElementGuid>9fcf94e2-b5b1-4a26-9320-92e4609e5e54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-paddingtop</name>
      <type>Main</type>
      <value>[0,0,0,0]</value>
      <webElementGuid>0d0b8cbe-e1a3-4de8-8802-e5283394899e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-paddingright</name>
      <type>Main</type>
      <value>[0,0,0,0]</value>
      <webElementGuid>57f43fe3-3a73-4e23-8f06-34d6eccef52b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-paddingbottom</name>
      <type>Main</type>
      <value>[0,0,0,0]</value>
      <webElementGuid>5ad664ec-2688-46ce-98b1-8111388afee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-paddingleft</name>
      <type>Main</type>
      <value>[0,0,0,0]</value>
      <webElementGuid>84b7dda5-00f5-4b06-bc3d-3123effb2c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get strong today
 </value>
      <webElementGuid>5fb3862b-a466-474c-b831-6d1f97a860a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slide-12-layer-10&quot;)</value>
      <webElementGuid>b78ceedd-7479-41f0-aecb-e58f732be2fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='slide-12-layer-10']</value>
      <webElementGuid>6e44ae3c-5148-446c-848c-00f78af1094e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rev_slider_6_1']/ul/li/div[5]/div/div/div</value>
      <webElementGuid>31144f9f-e9b1-4f04-9a4b-115483c31109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[3]/following::div[36]</value>
      <webElementGuid>04f787ef-1c4e-4188-9799-d58eb53c43c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='News'])[3]/following::div[36]</value>
      <webElementGuid>0c12c148-e640-47fe-81a3-5b8224dd2ef9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/preceding::div[10]</value>
      <webElementGuid>47b96fda-4289-49c7-86c3-6f60e2cfade8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sandy'])[1]/preceding::div[13]</value>
      <webElementGuid>29240537-8884-420e-8f33-737363c98819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Get strong today']/parent::*</value>
      <webElementGuid>61f6bc8f-49c9-43e4-be45-a6d9bfdcf173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div[5]/div/div/div</value>
      <webElementGuid>842d8408-ffbd-468e-b215-24454e8e6188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'slide-12-layer-10' and (text() = 'Get strong today
 ' or . = 'Get strong today
 ')]</value>
      <webElementGuid>fb6e0e0d-3e08-48a1-8272-2754ca904606</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
