<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Booking (step 1)_proj-responsiveimage p_3b6726</name>
   <tag></tag>
   <elementGuidId>e8e3f038-07ba-4dd2-9639-1e233c5c73c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='proj-landing']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.proj-responsiveimage.proj-margincenter.proj-margin30</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>img >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ce26f78f-9689-4b01-a2d9-74d6ecaded4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://booking.fitbybeat.com/html/media/logo.png</value>
      <webElementGuid>c36ebd36-3930-4ad7-8cf6-cd946f0f48f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>proj-responsiveimage proj-margincenter proj-margin30</value>
      <webElementGuid>24899926-dc2f-4624-92f4-38a1277818e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>68fa0728-55fa-49ec-b608-98a56d632815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;proj-landing&quot;)/img[@class=&quot;proj-responsiveimage proj-margincenter proj-margin30&quot;]</value>
      <webElementGuid>bd5ba10f-40c9-469b-8454-0900f01a5624</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='proj-landing']/img</value>
      <webElementGuid>84f15418-fff4-4122-a77d-b9ebf17c3ce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://booking.fitbybeat.com/html/media/logo.png')]</value>
      <webElementGuid>ecb2dd7e-10e7-4f3c-849e-b38b8651fb64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>cdcb6c03-90cd-4597-8bf8-8b15b275e0b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://booking.fitbybeat.com/html/media/logo.png']</value>
      <webElementGuid>d91ba8b3-3202-4a98-b221-bd99db721a29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
