<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select dateFriday, 27 August 2027</name>
   <tag></tag>
   <elementGuidId>3c9f5c40-d964-4afa-9e2e-da497c74bac5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='date_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#date_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#date_id</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0bd3520c-c15e-45a2-a564-10757ac0adbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-border</value>
      <webElementGuid>aa039db7-86d4-4cf0-aad4-90b039d34518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date_id</value>
      <webElementGuid>42e304a6-2808-4f17-83ca-c997b07effd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>date_id</value>
      <webElementGuid>a7aa07f4-a663-4c84-af33-710ad8204dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select dateFriday, 27 August 2027</value>
      <webElementGuid>0cce5746-010b-4b67-9938-7a7f23be7a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;date_id&quot;)</value>
      <webElementGuid>86e732c3-3e88-4deb-ae80-024586918497</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='date_id']</value>
      <webElementGuid>c79d142d-5758-47d9-a80d-7f22e74e0c6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='proj-landing']/form/div[2]/div/select</value>
      <webElementGuid>bc10eed3-124f-41bd-8058-2f6ae4d7e057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pick available date'])[1]/following::select[1]</value>
      <webElementGuid>f255d36a-b5e5-4355-b1a0-aeb4a95ef1f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a class'])[1]/following::select[2]</value>
      <webElementGuid>794b4307-7df1-4da2-b82a-ff5ed3703131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pick available hour'])[1]/preceding::select[1]</value>
      <webElementGuid>d0c2679f-9243-4a36-b3d4-51d78d2997c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity'])[1]/preceding::select[2]</value>
      <webElementGuid>68e1527b-593a-4ae4-ac1b-7ff56c138520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>b8a9ec19-0a60-434a-91e7-04caf2f5eb47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'date_id' and @id = 'date_id' and (text() = 'Select dateFriday, 27 August 2027' or . = 'Select dateFriday, 27 August 2027')]</value>
      <webElementGuid>5b7cc372-e14e-430c-98cf-5a3c3796ace5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
